#!/usr/bin/env bash

function up {
    surge . image-link.surge.sh && \
        now switch xieyuheng; now -n image-link deploy . --target production
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
